name: FB News Automation

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest news
        run: python -c "import urllib.request, xml.etree.ElementTree as ET; url='https://news.google.com/rss/search?q=Pratapgarh%20Uttar%20Pradesh&hl=hi&gl=IN&ceid=IN%3Ahi'; data=urllib.request.urlopen(url, timeout=20).read(); root=ET.fromstring(data); print('LATEST NEWS:'); [print('\nTITLE:', item.findtext('title'), '\nLINK:', item.findtext('link')) for item in root.findall('./channel/item')[:5]]"
